### ISSUE TITLE
Got Segmentation fault when attach a running progress.

### ISSUE THREAD

**Issue by hanke0** [NtesEyes/pylane#6]
OS: Linux rqams 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

GDB: GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7

Python version: 3.7.3

I tried to attach a running python progress, but the progress terminated with a Segmentation fault.

**Comment by dantangfan** [comment]
Sorry, Red Hat is not supported yet~
